package manifest

import (
	"os"
	"strings"
	"sort"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// FillFromSnippets assigns candidate GendocsKeys to manifest sections using keyword matching.
// For each candidate not already in any section:
//   - If manifest has exactly 1 section: assign to it.
//   - Otherwise: score each section slug by counting key-words (len>2) found in the slug;
//     assign to highest-scoring section if score > 0.
//   - If no section scores > 0 and pageHints are provided: fall back to scoring the candidate
//     against the page-path hint tokens; if score > 0, assign to the first alphabetically-sorted
//     empty section (generic-name fallback for sections like "implementation-example").
//
// pageHints should be the pre-extracted tokens from the page path — use PageHintsFromPath.
// Returns the count of newly assigned keys.
func FillFromSnippets(m *Manifest, candidates []string, pageHints ...string) int {
	sectionKeys := make([]string, 0, len(m.Sections))
	for k := range m.Sections {
		sectionKeys = append(sectionKeys, k)
	}
	sort.Strings(sectionKeys)
	if len(sectionKeys) == 0 {
		return 0
	}
	assigned := 0
	for _, key := range candidates {
		if keyExistsInAny(m, key) {
			continue
		}
		if len(sectionKeys) == 1 {
			sec := m.Sections[sectionKeys[0]]
			sec.Snippets = append(sec.Snippets, key)
			m.Sections[sectionKeys[0]] = sec
			assigned++
			continue
		}
		best, score := bestSectionForKey(sectionKeys, key)
		if score > 0 {
			sec := m.Sections[best]
			sec.Snippets = append(sec.Snippets, key)
			m.Sections[best] = sec
			assigned++
			continue
		}
		// Phase 2: page-path hint fallback for generic section names.
		if len(pageHints) > 0 && scoreKeyAgainstHints(key, pageHints) > 0 {
			target := firstEmptySection(sectionKeys, m)
			if target != "" {
				sec := m.Sections[target]
				sec.Snippets = append(sec.Snippets, key)
				m.Sections[target] = sec
				assigned++
			}
		}
	}
	return assigned
}

// PageHintsFromPath extracts meaningful tokens from the last two segments of a page path.
// Tokens are split by "-" and "_", and filtered to len > 2.
// Example: "social-plus-sdk/chat/message-creation/audio-message" → ["message", "creation", "audio"]
func PageHintsFromPath(pagePath string) []string {
	segs := strings.Split(filepath.ToSlash(pagePath), "/")
	// Take last 2 segments.
	start := len(segs) - 2
	if start < 0 {
		start = 0
	}
	seen := map[string]bool{}
	var hints []string
	for _, seg := range segs[start:] {
		for _, tok := range strings.FieldsFunc(seg, func(r rune) bool { return r == '-' || r == '_' }) {
			tok = strings.ToLower(tok)
			if len(tok) > 2 && !seen[tok] {
				seen[tok] = true
				hints = append(hints, tok)
			}
		}
	}
	return hints
}

// scoreKeyAgainstHints counts how many hint tokens appear as words in key (split by "-" and "_").
func scoreKeyAgainstHints(key string, hints []string) int {
	words := strings.FieldsFunc(key, func(r rune) bool { return r == '-' || r == '_' })
	score := 0
	for _, h := range hints {
		for _, w := range words {
			if strings.ToLower(w) == h {
				score++
				break
			}
		}
	}
	return score
}

// firstEmptySection returns the alphabetically first section slug with no snippets assigned.
func firstEmptySection(sectionKeys []string, m *Manifest) string {
	for _, sk := range sectionKeys {
		if len(m.Sections[sk].Snippets) == 0 {
			return sk
		}
	}
	return ""
}

// Header is the comment block prepended to every AUTO-GENERATED manifest file.
const Header = "# AUTO-GENERATED by harness genmanifests — fill in snippets: with GendocsKeys\n" +
	"# GendocsKey = DeriveKey(filename): strip 'Amity' prefix, PascalCase → kebab-case\n" +
	"# Example: AmityClientLogin.kt → client-login\n"

// SaveManifest writes m back to its file at docsDir/pagePath.manifest.yml,
// preserving the AUTO-GENERATED header comment.
func SaveManifest(docsDir, pagePath string, m *Manifest) error {
	outPath := PathForPage(docsDir, pagePath)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	out, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(Header+string(out)), 0o644)
}

func keyExistsInAny(m *Manifest, key string) bool {
	_, ok := m.SectionForSnippet(key)
	return ok
}

func bestSectionForKey(sectionKeys []string, key string) (string, int) {
	sort.Strings(sectionKeys)
	words := strings.Split(key, "-")
	best := ""
	bestScore := 0
	for _, sk := range sectionKeys {
		score := 0
		for _, w := range words {
			if len(w) > 2 && sectionContainsWord(sk, w) {
				score++
			}
		}
		if score > bestScore {
			bestScore = score
			best = sk
		}
	}
	return best, bestScore
}

func sectionContainsWord(sk, w string) bool {
	for _, part := range strings.Split(sk, "-") {
		if part == w {
			return true
		}
	}
	return false
}
