package manifest

import (
	"os"
	"strings"
	"sort"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// FillFromSnippets assigns candidate GendocsKeys to manifest sections using keyword matching.
// For each candidate not already in any section:
//   - If manifest has exactly 1 section: assign to it.
//   - Otherwise: score each section slug by counting key-words (len>2) found in the slug;
//     assign to highest-scoring section if score > 0.
//   - If no section scores > 0: leave unassigned (needs AI).
//
// Returns the count of newly assigned keys.
func FillFromSnippets(m *Manifest, candidates []string) int {
	sectionKeys := make([]string, 0, len(m.Sections))
	for k := range m.Sections {
		sectionKeys = append(sectionKeys, k)
	}
	sort.Strings(sectionKeys)
	if len(sectionKeys) == 0 {
		return 0
	}
	assigned := 0
	for _, key := range candidates {
		if keyExistsInAny(m, key) {
			continue
		}
		if len(sectionKeys) == 1 {
			sec := m.Sections[sectionKeys[0]]
			sec.Snippets = append(sec.Snippets, key)
			m.Sections[sectionKeys[0]] = sec
			assigned++
			continue
		}
		best, score := bestSectionForKey(sectionKeys, key)
		if score > 0 {
			sec := m.Sections[best]
			sec.Snippets = append(sec.Snippets, key)
			m.Sections[best] = sec
			assigned++
		}
	}
	return assigned
}

// Header is the comment block prepended to every AUTO-GENERATED manifest file.
const Header = "# AUTO-GENERATED by harness genmanifests — fill in snippets: with GendocsKeys\n" +
	"# GendocsKey = DeriveKey(filename): strip 'Amity' prefix, PascalCase → kebab-case\n" +
	"# Example: AmityClientLogin.kt → client-login\n"

// SaveManifest writes m back to its file at docsDir/pagePath.manifest.yml,
// preserving the AUTO-GENERATED header comment.
func SaveManifest(docsDir, pagePath string, m *Manifest) error {
	outPath := PathForPage(docsDir, pagePath)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	out, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(Header+string(out)), 0o644)
}

func keyExistsInAny(m *Manifest, key string) bool {
	_, ok := m.SectionForSnippet(key)
	return ok
}

func bestSectionForKey(sectionKeys []string, key string) (string, int) {
	sort.Strings(sectionKeys)
	words := strings.Split(key, "-")
	best := ""
	bestScore := 0
	for _, sk := range sectionKeys {
		score := 0
		for _, w := range words {
			if len(w) > 2 && sectionContainsWord(sk, w) {
				score++
			}
		}
		if score > bestScore {
			bestScore = score
			best = sk
		}
	}
	return best, bestScore
}

func sectionContainsWord(sk, w string) bool {
	for _, part := range strings.Split(sk, "-") {
		if part == w {
			return true
		}
	}
	return false
}
