#!/usr/bin/env python3
"""
ios-docc-extractor.py — Extract the iOS SDK public API surface from the prebuilt
xcframework's ABI JSON, producing a schema-compatible parallel to ios.json.

SOURCE: The `.abi.json` file embedded in AmitySDK.xcframework's .swiftmodule
is generated by the Swift compiler and contains the complete public ABI of the
prebuilt framework. It is structurally equivalent to what DocC's symbol graph
would provide (and is already available in our vendor directory without needing
to clone amity-ios-sdk-docc or run xcodebuild).

ABI JSON structure:
  ABIRoot.children[] — top-level declarations
    Each child: { kind, name, printedName, declKind, children[], declAttributes[], conformances[] }
    declKind: Class | Struct | Enum | Protocol | Func | Import | ...
    children: member declarations (Constructor | Func | Var | EnumElement | ...)
    printedName: includes parameter labels, e.g. "login(userId:displayName:)"
    children of a method: type nodes — first is return type, rest are param types

USAGE:
  python3 ios-docc-extractor.py [--abi-json PATH] [--output PATH]

  --abi-json  Path to .abi.json (default: auto-discovers from AmitySDK.xcframework
              in .docs-ops/integration-tests/ios/vendor/)
  --output    Output path (default: .docs-ops/sdk-surface/ios-from-docc.json)
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
DOCS_OPS_DIR = SCRIPT_DIR.parent
VENDOR_DIR   = DOCS_OPS_DIR / "integration-tests" / "ios" / "vendor"

DEFAULT_ABI_JSON = (
    VENDOR_DIR
    / "AmitySDK.xcframework"
    / "ios-arm64_x86_64-simulator"
    / "AmitySDK.framework"
    / "Modules"
    / "AmitySDK.swiftmodule"
    / "x86_64-apple-ios-simulator.abi.json"
)
DEFAULT_OUTPUT = DOCS_OPS_DIR / "sdk-surface" / "ios-from-docc.json"

VERSION = "0.2.0-abi"

# declKind values that are top-level named types
TYPE_DECL_KINDS = {"Class", "Struct", "Enum", "Protocol"}

# member declKind values we surface (covers methods, vars, cases, nested types)
MEMBER_DECL_KINDS = {
    "Constructor", "Func", "Var", "Let", "EnumElement",
    "TypeAlias", "AssociatedType", "Subscript",
}

# Top-level standalone declarations (not nested inside a type)
GLOBAL_FUNC_KINDS  = {"Func"}
GLOBAL_CONST_KINDS = {"Var", "Let"}
GLOBAL_ALIAS_KINDS = {"TypeAlias"}


def _decl_kind_to_surface_kind(decl_kind: str) -> str:
    mapping = {
        "Class":         "class",
        "Struct":        "struct",
        "Enum":          "enum",
        "Protocol":      "protocol",
        "Constructor":   "init",
        "Func":          "func",
        "Var":           "var",
        "Let":           "let",
        "EnumElement":   "case",
        "TypeAlias":     "typealias",
        "AssociatedType":"associatedtype",
        "Subscript":     "subscript",
    }
    return mapping.get(decl_kind, decl_kind.lower())


def _parse_signature(node: dict) -> dict | None:
    """
    Extract a structured signature from a method/constructor ABI node.
    Returns {parameters: [{label, type}], returns: str} or None for non-callables.
    """
    printed = node.get("printedName", "")
    if "(" not in printed:
        return None  # not a callable

    type_nodes = node.get("children", [])
    if not type_nodes:
        return None

    # First child = return type; remaining = parameter types (in declaration order)
    return_node  = type_nodes[0] if type_nodes else None
    param_nodes  = type_nodes[1:] if len(type_nodes) > 1 else []

    # Extract parameter labels from printedName: "foo(label1:label2:)"
    label_match = re.search(r'\(([^)]*)\)', printed)
    raw_labels  = label_match.group(1).split(":") if label_match else []
    labels      = [l.strip() for l in raw_labels if l.strip()]

    parameters = []
    for i, pnode in enumerate(param_nodes):
        label = labels[i] if i < len(labels) else "_"
        parameters.append({
            "label": label,
            "type":  pnode.get("printedName", "?"),
        })

    return {
        "parameters": parameters,
        "returns":    return_node.get("printedName", "Void") if return_node else "Void",
    }


def _build_member_entry(node: dict) -> dict:
    entry = {
        "name":         node["name"],
        "kind":         _decl_kind_to_surface_kind(node.get("declKind", "")),
        "printed_name": node.get("printedName", node["name"]),
        "file":         "",   # prebuilt framework — no source location available
        "line":         None,
    }
    sig = _parse_signature(node)
    if sig is not None:
        entry["signature"] = sig  # bonus v2 field — ignored by current validators
    return entry


def _is_internal_type_name(name: str) -> bool:
    """
    Filter heuristic for TOP-LEVEL type names only.
    Names starting with _ are compiler-internal (e.g. _ConcreteTypeBox).
    Note: we do NOT filter 'Internal'/'Private' substrings from member names —
    the ABI JSON only surfaces public/open declarations, so any member that
    appears in the ABI is public regardless of what its name contains.
    """
    return name.startswith("_")


def extract(abi_json_path: Path) -> dict:
    with open(abi_json_path) as f:
        abi = json.load(f)

    top_children = abi.get("ABIRoot", {}).get("children", [])

    types:             dict = {}
    protocols:         dict = {}
    global_funcs:      list = []
    global_consts:     list = []
    global_typealiases:list = []

    for node in top_children:
        decl_kind = node.get("declKind", "")
        name      = node.get("name", "")

        if not name or decl_kind == "Import":
            continue
        if _is_internal_type_name(name):
            continue

        if decl_kind in TYPE_DECL_KINDS:
            members      = []
            nested_types = []

            for child in node.get("children", []):
                child_kind = child.get("declKind", "")
                child_name = child.get("name", "")
                if not child_name:
                    continue
                # For nested type names, apply the type-name filter; members are always public in ABI
                if child_kind in TYPE_DECL_KINDS and _is_internal_type_name(child_name):
                    continue

                if child_kind in MEMBER_DECL_KINDS:
                    members.append(_build_member_entry(child))
                elif child_kind in TYPE_DECL_KINDS:
                    nested_types.append({
                        "name":         child_name,
                        "kind":         _decl_kind_to_surface_kind(child_kind),
                        "printed_name": child.get("printedName", child_name),
                        "primary_decl": {"file": "", "line": None},
                        "members": [
                            _build_member_entry(m)
                            for m in child.get("children", [])
                            if m.get("declKind") in MEMBER_DECL_KINDS
                        ],
                    })

            conformances = [
                c["name"] for c in node.get("conformances", [])
                if not c["name"].startswith("_") and c["name"] not in ("Copyable", "Sendable", "Escapable")
            ]

            entry = {
                "kind":         _decl_kind_to_surface_kind(decl_kind),
                "primary_decl": {"file": "", "line": None},
                "members":      members,
                "nested_types": nested_types,
                "conformances": conformances,
                "extensions":   [],
            }

            target = protocols if decl_kind == "Protocol" else types
            target[name] = entry

        elif decl_kind in GLOBAL_FUNC_KINDS:
            entry = _build_member_entry(node)
            entry["namespace"] = None
            global_funcs.append(entry)

        elif decl_kind in GLOBAL_CONST_KINDS:
            entry = _build_member_entry(node)
            entry["namespace"] = None
            global_consts.append(entry)

        elif decl_kind in GLOBAL_ALIAS_KINDS:
            global_typealiases.append({"name": name, "kind": "typealias", "file": "", "line": None})

    # Stats
    members_total = sum(len(v["members"]) for v in types.values()) + \
                    sum(len(v["members"]) for v in protocols.values())
    nested_total  = sum(len(v["nested_types"]) for v in types.values())
    enum_cases    = sum(
        sum(1 for m in v["members"] if m["kind"] == "case")
        for v in types.values()
        if v["kind"] == "enum"
    )

    surface = {
        "extractor_version":  VERSION,
        "extractor":          "ios-docc-extractor.py",
        "extracted_at":       datetime.now(timezone.utc).isoformat(),
        "sdk_product":        "AmitySDK",
        "sdk_docc_archive":   str(abi_json_path),
        "source_format":      "swiftmodule-abi-json",
        "note":               (
            "Surface extracted from the prebuilt xcframework's .abi.json. "
            "This is the compiled public ABI — equivalent in coverage to DocC's "
            "symbol graph but sourced from the vendor xcframework already in this repo. "
            "No source file:line locations are available (prebuilt binary)."
        ),
        "types":              types,
        "protocols":          protocols,
        "global_funcs":       global_funcs,
        "global_consts":      global_consts,
        "global_typealiases": global_typealiases,
        "stats": {
            "types_total":          len(types),
            "protocols_total":      len(protocols),
            "members_total":        members_total,
            "nested_types_total":   nested_total,
            "enum_cases_total":     enum_cases,
            "global_funcs":         len(global_funcs),
            "global_consts":        len(global_consts),
            "global_typealiases":   len(global_typealiases),
            "source_file_line_available": False,
        },
    }
    return surface


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--abi-json", type=Path, default=DEFAULT_ABI_JSON,
                    help="Path to .abi.json from xcframework swiftmodule")
    ap.add_argument("--output",   type=Path, default=DEFAULT_OUTPUT,
                    help="Output path for ios-from-docc.json")
    args = ap.parse_args()

    if not args.abi_json.exists():
        print(f"[ios-docc-extractor] ERROR: abi-json not found: {args.abi_json}", file=sys.stderr)
        sys.exit(1)

    print(f"[ios-docc-extractor] reading {args.abi_json}")
    surface = extract(args.abi_json)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(surface, indent=2) + "\n")

    s = surface["stats"]
    print(f"[ios-docc-extractor] wrote {args.output}")
    print(f"[ios-docc-extractor] types={s['types_total']} protocols={s['protocols_total']} "
          f"members={s['members_total']} nested={s['nested_types_total']} "
          f"global_funcs={s['global_funcs']}")


if __name__ == "__main__":
    main()
