package docgen_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"social-plus/harness/internal/docgen"
	"social-plus/harness/internal/scanner"

	"github.com/stretchr/testify/assert"
)

func TestDeriveKey(t *testing.T) {
	cases := []struct {
		filename string
		want     string
	}{
		{"AmityCommunityMembershipAddMembers.kt", "community-membership-add-members"},
		{"AmityPostCreateTextPost.swift", "post-create-text-post"},
		{"AmityChannelGet.dart", "channel-get"},
		{"AmityUserGetByIds.ts", "user-get-by-ids"},
		{"AmityStoryGetActiveStories.dart", "story-get-active-stories"},
	}
	for _, tc := range cases {
		t.Run(tc.filename, func(t *testing.T) {
			assert.Equal(t, tc.want, docgen.DeriveKey(tc.filename))
		})
	}
}

func TestDeriveMDXPath(t *testing.T) {
	cases := []struct {
		ascPage string
		key     string
		want    string
	}{
		{
			"social-plus-sdk/social/communities-spaces/community-lifecycle/create-community",
			"community-create",
			"social-plus-sdk/social/community-create.mdx",
		},
		{
			"social-plus-sdk/chat/messaging-features/messages/create-message",
			"message-create-text-message",
			"social-plus-sdk/chat/message-create-text-message.mdx",
		},
		{
			"uikit/components/social/posts",
			"post-create-text-post",
			"uikit/components/post-create-text-post.mdx",
		},
	}
	for _, tc := range cases {
		t.Run(tc.key, func(t *testing.T) {
			assert.Equal(t, tc.want, docgen.DeriveMDXPath(tc.ascPage, tc.key))
		})
	}
}

func TestGroupSnippets(t *testing.T) {
	snips := []scanner.Snippet{
		{Filename: "AmityCommunityCreate.kt", AscPage: "social-plus-sdk/social/communities/create", Description: "Create a community", Content: "android code", Platform: "android"},
		{Filename: "AmityCommunityCreate.swift", AscPage: "social-plus-sdk/social/communities/create", Description: "Create a community", Content: "ios code", Platform: "ios"},
		{Filename: "AmityCommunityCreate.dart", AscPage: "social-plus-sdk/social/communities/create", Description: "Create a community", Content: "flutter code", Platform: "flutter"},
		{Filename: "AmityPostCreateTextPost.kt", AscPage: "social-plus-sdk/social/posts/create-post", Description: "Create text post", Content: "android post", Platform: "android"},
	}

	groups := docgen.GroupSnippets(snips)

	assert.Len(t, groups, 2)

	communityGroup, ok := groups["community-create"]
	assert.True(t, ok, "community-create group should exist")
	assert.Equal(t, "social-plus-sdk/social/communities/create", communityGroup.AscPage)
	assert.Equal(t, "Create a community", communityGroup.Description)
	assert.Equal(t, "android code", communityGroup.Snippets["android"].Content)
	assert.Equal(t, "ios code", communityGroup.Snippets["ios"].Content)
	assert.Equal(t, "flutter code", communityGroup.Snippets["flutter"].Content)

	postGroup, ok := groups["post-create-text-post"]
	assert.True(t, ok, "post-create-text-post group should exist")
	assert.Equal(t, "android post", postGroup.Snippets["android"].Content)
}

func TestRenderMDX(t *testing.T) {
	group := docgen.SnippetGroup{
		Key:         "community-create",
		AscPage:     "social-plus-sdk/social/communities/create",
		Description: "Create a community",
		Snippets: map[string]scanner.Snippet{
			"android": {Content: "android code here", Platform: "android"},
			"ios":     {Content: "ios code here", Platform: "ios"},
		},
	}

	out := docgen.RenderMDX(group, "2026-04-30")

	assert.Contains(t, out, "{/* AUTO-GENERATED by harness gendocs")
	assert.Contains(t, out, "function: community-create")
	assert.Contains(t, out, "<CodeGroup>")
	assert.Contains(t, out, "```kotlin Android")
	assert.Contains(t, out, "android code here")
	assert.Contains(t, out, "```swift iOS")
	assert.Contains(t, out, "ios code here")
	assert.NotContains(t, out, "```dart Flutter")
	assert.NotContains(t, out, "```typescript TypeScript")
	assert.NotContains(t, out, "begin_sample_code")
	assert.NotContains(t, out, "end_sample_code")
}

func TestRenderMDXPlatformOrder(t *testing.T) {
	group := docgen.SnippetGroup{
		Key: "post-create",
		Snippets: map[string]scanner.Snippet{
			"typescript": {Content: "ts code", Platform: "typescript"},
			"flutter":    {Content: "flutter code", Platform: "flutter"},
			"android":    {Content: "android code", Platform: "android"},
			"ios":        {Content: "ios code", Platform: "ios"},
		},
	}
	out := docgen.RenderMDX(group, "2026-04-30")
	androidIdx := strings.Index(out, "```kotlin Android")
	iosIdx := strings.Index(out, "```swift iOS")
	flutterIdx := strings.Index(out, "```dart Flutter")
	typescriptIdx := strings.Index(out, "```typescript TypeScript")
	assert.Less(t, androidIdx, iosIdx)
	assert.Less(t, iosIdx, flutterIdx)
	assert.Less(t, flutterIdx, typescriptIdx)
}

func TestWrite(t *testing.T) {
	outDir := t.TempDir()
	groups := map[string]docgen.SnippetGroup{
		"community-create": {
			Key:     "community-create",
			AscPage: "social-plus-sdk/social/communities/create",
			Snippets: map[string]scanner.Snippet{
				"android": {Content: "android code", Platform: "android"},
			},
		},
	}

	written, skipped, err := docgen.Write(outDir, groups, false)
	assert.NoError(t, err)
	assert.Equal(t, 1, written)
	assert.Equal(t, 0, skipped)

	mdxPath := filepath.Join(outDir, "social-plus-sdk", "social", "community-create.mdx")
	b, err := os.ReadFile(mdxPath)
	assert.NoError(t, err)
	assert.Contains(t, string(b), "AUTO-GENERATED")
	assert.Contains(t, string(b), "android code")
}

func TestWriteSkipsHumanEdited(t *testing.T) {
	outDir := t.TempDir()
	mdxPath := filepath.Join(outDir, "social-plus-sdk", "social", "community-create.mdx")
	assert.NoError(t, os.MkdirAll(filepath.Dir(mdxPath), 0755))
	assert.NoError(t, os.WriteFile(mdxPath, []byte("# Human written\n"), 0644))

	groups := map[string]docgen.SnippetGroup{
		"community-create": {
			Key:     "community-create",
			AscPage: "social-plus-sdk/social/communities/create",
			Snippets: map[string]scanner.Snippet{
				"android": {Content: "android code", Platform: "android"},
			},
		},
	}

	written, skipped, err := docgen.Write(outDir, groups, false)
	assert.NoError(t, err)
	assert.Equal(t, 0, written)
	assert.Equal(t, 1, skipped)

	b, _ := os.ReadFile(mdxPath)
	assert.Equal(t, "# Human written\n", string(b))
}

func TestWriteDryRun(t *testing.T) {
	outDir := t.TempDir()
	groups := map[string]docgen.SnippetGroup{
		"community-create": {
			Key:     "community-create",
			AscPage: "social-plus-sdk/social/communities/create",
			Snippets: map[string]scanner.Snippet{
				"android": {Content: "android code", Platform: "android"},
			},
		},
	}

	written, _, err := docgen.Write(outDir, groups, true)
	assert.NoError(t, err)
	assert.Equal(t, 1, written)

	mdxPath := filepath.Join(outDir, "social-plus-sdk", "social", "community-create.mdx")
	_, statErr := os.Stat(mdxPath)
	assert.True(t, os.IsNotExist(statErr), "dry-run must not write files")
}

func TestWriteManifest(t *testing.T) {
	outDir := t.TempDir()
	groups := map[string]docgen.SnippetGroup{
		"community-create": {Key: "community-create", AscPage: "social-plus-sdk/social/communities/create"},
		"post-create":      {Key: "post-create", AscPage: "social-plus-sdk/social/posts/create"},
	}

	err := docgen.WriteManifest(outDir, groups, false)
	assert.NoError(t, err)

	b, err := os.ReadFile(filepath.Join(outDir, "manifest.json"))
	assert.NoError(t, err)

	var m map[string]string
	assert.NoError(t, json.Unmarshal(b, &m))
	assert.Equal(t, "social-plus-sdk/social/community-create.mdx", m["community-create"])
	assert.Equal(t, "social-plus-sdk/social/post-create.mdx", m["post-create"])
}
