package docgen

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"
	"unicode"

	"social-plus/harness/internal/scanner"
)

// DeriveKey converts a snippet filename to a URL-safe grouping key.
// "AmityCommunityMembershipAddMembers.kt" → "community-membership-add-members"
func DeriveKey(filename string) string {
	base := filename
	if idx := strings.LastIndex(base, "."); idx >= 0 {
		base = base[:idx]
	}
	if strings.HasPrefix(strings.ToLower(base), "amity") {
		base = base[5:]
	}
	return pascalToKebab(base)
}

// DeriveMDXPath returns the relative MDX output path for a snippet group.
// Uses the first two segments of ascPage as directory + key as filename.
func DeriveMDXPath(ascPage, key string) string {
	segs := strings.SplitN(ascPage, "/", 3)
	dir1 := safeSegment(segs, 0)
	dir2 := safeSegment(segs, 1)
	return path.Join(dir1, dir2, key+".mdx")
}

func safeSegment(segs []string, i int) string {
	if i < len(segs) {
		return segs[i]
	}
	return "unknown"
}

func pascalToKebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			b.WriteRune('-')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// SnippetGroup holds all platform snippets for one logical function.
type SnippetGroup struct {
	Key         string
	SpDocsPage  string
	Description string
	Snippets    map[string]scanner.Snippet // platform → snippet
}

// GroupSnippets groups a flat list of snippets by their derived key.
// Snippets with a blank Filename, blank SpDocsPage, or an absolute URL SpDocsPage are skipped.
// Input is sorted deterministically (platform priority: android → ios → flutter → typescript)
// so that the first platform processed always wins for SpDocsPage — making output stable.
func GroupSnippets(snips []scanner.Snippet) map[string]SnippetGroup {
	platformPriority := map[string]int{"android": 0, "ios": 1, "flutter": 2, "typescript": 3}
	sorted := make([]scanner.Snippet, len(snips))
	copy(sorted, snips)
	sort.SliceStable(sorted, func(i, j int) bool {
		pi := platformPriority[sorted[i].Platform]
		pj := platformPriority[sorted[j].Platform]
		if pi != pj {
			return pi < pj
		}
		return sorted[i].Filename < sorted[j].Filename
	})

	groups := make(map[string]SnippetGroup)
	for _, s := range sorted {
		if s.Filename == "" || s.SpDocsPage == "" || strings.Contains(s.SpDocsPage, "://") {
			continue
		}
		key := DeriveKey(s.Filename)
		if key == "" {
			continue
		}
		g, exists := groups[key]
		if !exists {
			g = SnippetGroup{
				Key:         key,
				SpDocsPage:  s.SpDocsPage,
				Description: s.Description,
				Snippets:    make(map[string]scanner.Snippet),
			}
		}
		g.Snippets[s.Platform] = s
		groups[key] = g
	}
	return groups
}

var platformOrder = []string{"android", "ios", "flutter", "typescript"}

var platformLabel = map[string]string{
	"android":    "Android",
	"ios":        "iOS",
	"flutter":    "Flutter",
	"typescript": "TypeScript",
}

var platformFence = map[string]string{
	"android":    "kotlin",
	"ios":        "swift",
	"flutter":    "dart",
	"typescript": "typescript",
}

// RenderMDX generates the MDX content for a snippet group.
// date is used in the generated header comment (format: "YYYY-MM-DD").
func RenderMDX(group SnippetGroup, date string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{/* AUTO-GENERATED by harness gendocs — do not edit manually */}\n")
	fmt.Fprintf(&b, "{/* function: %s | updated: %s */}\n\n", group.Key, date)
	b.WriteString("<CodeGroup>\n")
	for _, platform := range platformOrder {
		snip, ok := group.Snippets[platform]
		if !ok {
			continue
		}
		fence := platformFence[platform]
		label := platformLabel[platform]
		fmt.Fprintf(&b, "\n```%s %s\n%s\n```\n", fence, label, snip.Content)
	}
	b.WriteString("\n</CodeGroup>\n")
	return b.String()
}

const autoGeneratedMarker = "AUTO-GENERATED by harness gendocs"

// CleanDir removes all AUTO-GENERATED MDX files from outDir (recursively).
// Returns the count of removed files. Human-edited files are left untouched.
func CleanDir(outDir string) (removed int, err error) {
	return removed, filepath.WalkDir(outDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() {
			return walkErr
		}
		if !strings.HasSuffix(path, ".mdx") {
			return nil
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if strings.Contains(string(content), autoGeneratedMarker) {
			if delErr := os.Remove(path); delErr != nil {
				return delErr
			}
			removed++
		}
		return nil
	})
}

// Write generates MDX files for all groups under outDir.
// Returns counts of files written and skipped (human-edited).
// In dry-run mode, counts planned writes but touches no files.
func Write(outDir string, groups map[string]SnippetGroup, dryRun bool, log io.Writer) (written, skipped int, err error) {
	date := time.Now().Format("2006-01-02")
	for _, group := range groups {
		relPath := DeriveMDXPath(group.SpDocsPage, group.Key)
		absPath := filepath.Join(outDir, filepath.FromSlash(relPath))

		if existing, readErr := os.ReadFile(absPath); readErr == nil {
			if !strings.Contains(string(existing), autoGeneratedMarker) {
				fmt.Fprintf(log, "[gendocs] SKIP (human-edited): %s\n", relPath)
				skipped++
				continue
			}
		}

		content := RenderMDX(group, date)
		fmt.Fprintf(log, "[gendocs] WRITE: %s\n", relPath)
		written++

		if dryRun {
			continue
		}

		if mkErr := os.MkdirAll(filepath.Dir(absPath), 0755); mkErr != nil {
			return written, skipped, fmt.Errorf("mkdir %s: %w", filepath.Dir(absPath), mkErr)
		}
		if writeErr := os.WriteFile(absPath, []byte(content), 0644); writeErr != nil {
			return written, skipped, fmt.Errorf("write %s: %w", absPath, writeErr)
		}
	}
	return written, skipped, nil
}

// WriteManifest writes manifest.json mapping function key → MDX relative path.
func WriteManifest(outDir string, groups map[string]SnippetGroup, dryRun bool, log io.Writer) error {
	manifest := make(map[string]string, len(groups))
	for key, group := range groups {
		manifest[key] = DeriveMDXPath(group.SpDocsPage, key)
	}

	b, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}

	manifestPath := filepath.Join(outDir, "manifest.json")
	fmt.Fprintf(log, "[gendocs] WRITE manifest: %s\n", manifestPath)
	if dryRun {
		return nil
	}
	if mkErr := os.MkdirAll(outDir, 0755); mkErr != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, mkErr)
	}
	return os.WriteFile(manifestPath, b, 0644)
}
